apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-bench.fullname" . }}
  labels:
    {{- include "agent-bench.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7860
      protocol: TCP
      name: http
  selector:
    {{- include "agent-bench.selectorLabels" . | nindent 4 }}
